version: "3.2"
services:
  marketplace-3:
    build:
      dockerfile: ./Dockerfile
      context: ./marketplace-3/
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - redis-commander

  stock-2:
    build:
      dockerfile: ./Dockerfile
      context: ./stock-2/
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - redis
      - redis-commander 

  postgres:
    image: postgres
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
    - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis